name: CD

on:
  push:
    branches:
      - dev
      - staging
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      # 🔁 Map branch → environment
      - name: Set Environment Name
        id: set-env
        run: |
          if [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            echo "ENV=prod" >> $GITHUB_OUTPUT
          else
            echo "ENV=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
          fi

      # 🔐 OIDC Auth
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/skynet-ops-audit-service-${{ steps.set-env.outputs.ENV }}-github-actions-role
          aws-region: us-east-1

      # 🐳 Login ECR
      - name: Login to ECR
        run: |
          aws ecr get-login-password --region us-east-1 | \
          docker login --username AWS --password-stdin \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com

      # 🐳 Build & Push
      - name: Build & Push Image
        run: |
          IMAGE=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/skynet-ops-audit-service-${{ steps.set-env.outputs.ENV }}:latest
          docker buildx build --platform linux/amd64 --provenance=false -t $IMAGE --push .

      # 🏗 Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      # 🚀 Deploy Infra
      - name: Terraform Deploy
        run: |
          cd infra/terraform/envs/${{ steps.set-env.outputs.ENV }}
          terraform init -input=false
          terraform apply -auto-approve -var-file=terraform.tfvars